### ISSUE TITLE
On a specific email address the application fails

### ISSUE THREAD

**Issue by carouselcarousel** [pixelbubble/ProtOSINT#2]
Protonmail API is ONLINE
Protonmail VPN is ONLINE

Let's take a look at your target:
1 - Test the validity of one protonmail account
2 - Try to find if your target have a protonmail account
3 - Find if your IP is currently affiliate to ProtonVPN

Choose a program: 1
You want to know if a protonmail email is real ?
Give me your email: soXXXXXXXXXXXX8@protonmail.com
Protonmail email is valid
Traceback (most recent call last):
  File "/root/Downloads/ProtOSINT/protosint.py", line 94, in checkValidityOneAccount
    timestamp = int(re.search(regexPattern1, bodyResponse).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Downloads/ProtOSINT/protosint.py", line 246, in <module>
    main()
  File "/root/Downloads/ProtOSINT/protosint.py", line 239, in main
    checkValidityOneAccount() 
  File "/root/Downloads/ProtOSINT/protosint.py", line 96, in checkValidityOneAccount
    timestamp = int(re.search(regexPattern2, bodyResponse).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

Note:
I can lookup other email addresses and works jsut fine, no issues there. I don't know what is special about this email address.
(Sad I need to mask it out because of privacy, but I can share it in PM when needed)

**Comment by pixelbubble** [comment]
Hi. Thanks for this issue. Can you send your specific email address to thisisatestemailaccount@protonmail.com?

**Comment by carouselcarousel** [comment]
please remove the shared email address after you read/tested it. Thank you.
solutioncenter88@
protonmail.com

**Comment by pixelbubble** [comment]
I just checked and it works for me:

Choose a program: 1
You want to know if a protonmail email is real ?
Give me your email: so************8@protonmail.com
Protonmail email is valid
Date and time of the creation: 2021-10-05 16:32:36
Encryption : X25519 (Modern, fastest, secure)
Do you want to download the public key attached to the email ?
Please enter "yes" or "no": no
